//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commons_Utility_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }

        public int Order_ID { get; set; }
        public string Customer_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Ship_Name { get; set; }
        public string Ship_Address { get; set; }
        public string Ship_City { get; set; }
        public string Ship_Region { get; set; }
        public string Ship_Postal_Code { get; set; }
        public string Ship_Country { get; set; }
        public Nullable<int> Ship_Via { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.DateTime> Required_Date { get; set; }
        public Nullable<System.DateTime> Shipped_Date { get; set; }
        public Nullable<decimal> Freight { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Shippers Shippers { get; set; }
    }
}
